### ISSUE TITLE
Cmake error when compiling on Arch

### ISSUE THREAD

**Issue by larevehkaoja** [ChrisAJS/lgx2userspace#19]
1. I have installed all dependencies
2. I have been able to compile this project before 

Cmake throws me an error when "Building CXX object src/gtk/CMakeFiles/lgx2userspace-gtk.dir/src/lgxsession.cpp.o (at 96%)". 

![error](https://user-images.githubusercontent.com/112462385/189475679-82b168dc-ee91-4076-8383-d0c981e0d51e.png)

**Comment by Nama** [comment]
Latest commits require `gtk4` to build. The readme was not updated.

**Comment by larevehkaoja** [comment]
It fails on same file even when I installed `gtk4`

**Comment by ChuckyAtBSG** [comment]
Ever since I made support for the LGX a compile time option, this would have been broken. The GTK4 front-end is not fit for purpose though. I'm going to make it a separate subproject I think. I'll get a fix pushed for now though.

**Comment by ChrisAJS** [comment]
[This commit](https://github.com/ChrisAJS/lgx2userspace/commit/481f2de4d3fd5218c6162d8312373c88ea300767) fixes the issue.

Let me know if you get it building and I'll close this issue, otherwise you're free to close it yourself, cheers.

**Comment by Nama** [comment]
Works now, thank you!

**Comment by larevehkaoja** [comment]
Compiles fine :) Thanks for quick fix!

**Comment by ChuckyAtBSG** [comment]
Awesome, feel free to close the issue. Have a good day!
