### ISSUE TITLE
HDMI pass-thru doesn't work if lgx2userspace is not started

### ISSUE THREAD

**Issue by Nama** [ChrisAJS/lgx2userspace#22]
Since I used lgx2userspace, HDMI pass-thru only works if I start lgx2userspace once. I can even close it again, it still works.
That might be an issue of not de-initialising (#18), just a guess, tho^^
I still didn't try Windows again...

1. Unplug LGX2 USB cable (For me, the unplugged time was always over night)
2. Plug LGX2 USB cable
3. *Don't* start `lgx2userspace`
4. Check if pass-thru works
5. Start `lgx2userspace`
6. Pass-thru should work now

**Comment by ChrisAJS** [comment]
Hi,

Yeah the HDMI pass-thru will remain active the entire time after you have started the lgx2userspace program.

The device remains in a state and there is no tear down that happens at all currently. 

I'm going to close this, but if you need to add anything feel free to open it back up! Cheers!
