### ISSUE TITLE
Does the released build support GC550? 

### ISSUE THREAD

**Issue by Rhyme** [ChrisAJS/lgx2userspace#23]
TSIA. I'm on Windows 11, which has no native support for the GC550. I can't use the official software at all.

I'm encountering some strange issues trying to use the Windows release out of the box; no audio and after just a couple of minutes the display bugs out. Pictures related.

![image](https://user-images.githubusercontent.com/11220496/202837471-bf3154fc-b924-423c-a2d7-a26f50e11387.png)

![image](https://user-images.githubusercontent.com/11220496/202837476-6bd009e6-84b7-4472-8062-dba1edce23f1.png)

If the GC550 isn't supported in the build (per the readme, it's disabled by default, I think?), how do I build it with support for that device *from Windows*? 

Thank you.

**Comment by ChrisAJS** [comment]
Hi there,

I can't remember whether or not it was supported in that build but for you to get to the point where there is video output (despite being corrupt!) does suggest that it does contain the support.

I've struggled to get the performance out of the binaries when compiling sdl2 as part of the process (which is what I did for the windows build).

Knowing that there is someone using it I'll focus on this next. Especially given that it just isn't supported!

**Comment by Rhyme** [comment]
Thank you so much! If you need me to test anything let me know, would be happy to help where I can!

**Comment by Baoulettes** [comment]
You may try to launch it with the argument -x like on Linux or MacOS to make it working fine :)
![GC550 Win 11](https://www.baoulettes.fr/Uploads/d9w0lxgb6yhj30ubvbapit3dy.png)

**Comment by ChrisAJS** [comment]
Out of interest, if the tool created a virtual webcam / video source, would that also be acceptable?

**Comment by Baoulettes** [comment]
About no sound I do have the same issues and never noticed (I am the kind of guy to play without sound and music only ^^)

**Comment by ChrisAJS** [comment]
Apologies for taking so long to get back to you. 

I had a nightmare this morning attempting to get video capture to work at all for me.

It can't be stressed enough, that you need USB cables that ship with the device in order for the data rate to be sufficient to capture frames.

Also, FWIW, if you're using something like the Genki Stealth Dock, you need to be using a USB cable that is also capable of thunderbolt 3 (i.e. one of those thick boys that comes with a Monitor that can be driven via USB-C.)

**Data capture will not function if you are not using good enough cables.**

**Comment by ChrisAJS** [comment]
@Rhyme sorry for taking so long to get this out but [0.3.0 release](https://github.com/ChrisAJS/lgx2userspace/releases/tag/release%2F0.3.0) contains a version of the software that uses GLFW as an underlying rendering system. 

This should reduce the time to render frames which can lead to garbled output (when rendering a frame takes too long, the device loses sync.)

If you can give the GLFW version a go, maybe it'll solve the problem for you. There is a GC550 specific binary to try which eliminates the need for clarification on whether the release supports the card.

Cheers!
