### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ChiAkuma** [ChrisAJS/lgx2userspace#27]
**Describe the bug**

**To Reproduce**
1. install for arch from aur or follow cmake
2. on cmake it has error that libsdl.org does not exists

**Expected behaviour**
building successfully

**Screenshots**
xorg/system: System requirements:  already installed

======== Installing packages ========
egl/system: Already installed! (1 of 34)
expat/2.5.0: Already installed! (2 of 34)
glad/0.1.36: Already installed! (3 of 34)
libcap/2.66: Already installed! (4 of 34)
libffi/3.4.3: Already installed! (5 of 34)
libiconv/1.17: Already installed! (6 of 34)
libudev/system: Already installed! (7 of 34)
m4/1.4.19: Already installed! (8 of 34)
m4/1.4.19: Appending PATH environment variable: /home/chiakuma/.conan2/p/m4328c8d04ee36f/p/bin
ogg/1.3.5: Already installed! (9 of 34)
opengl/system: Already installed! (10 of 34)
openssl/1.1.1t: Already installed! (11 of 34)
opus/1.3.1: Already installed! (12 of 34)
xkeyboard-config/system: Already installed! (13 of 34)
xorg/system: Already installed! (14 of 34)
xz_utils/5.4.0: Already installed! (15 of 34)
zlib/1.2.13: Already installed! (16 of 34)
libmp3lame/3.100: Already installed! (17 of 34)
pkgconf/1.9.3: Already installed! (18 of 34)
pkgconf/1.9.3: Appending PATH env var: /home/chiakuma/.conan2/p/pkgcod729a37c3fef7/p/bin
pkgconf/1.9.3: Setting PKG_CONFIG env var: /home/chiakuma/.conan2/p/pkgcod729a37c3fef7/p/bin/pkgconf
pkgconf/1.9.3: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
pkgconf/1.9.3: Appending AUTOMAKE_CONAN_INCLUDES env var: /home/chiakuma/.conan2/p/pkgcod729a37c3fef7/p/bin/aclocal
mpg123/1.31.2: Already installed! (19 of 34)
mpg123/1.31.2: Appending PATH environment variable: /home/chiakuma/.conan2/p/mpg12bdf5d43fe1eb0/p/bin
libalsa/1.2.7.2: Already installed! (20 of 34)
autoconf/2.71: Already installed! (21 of 34)
autoconf/2.71: Defining AC_MACRODIR environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/res/autoconf
autoconf/2.71: Defining autom4te_perllibdir environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/res/autoconf
autoconf/2.71: Defining AUTOCONF environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/bin/autoconf
autoconf/2.71: Defining AUTORECONF environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/bin/autoreconf
autoconf/2.71: Defining AUTOHEADER environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/bin/autoheader
autoconf/2.71: Defining AUTOM4TE environment variable: /home/chiakuma/.conan2/p/autoc84ad36d1c05b9/p/bin/autom4te
flac/1.4.2: Already installed! (22 of 34)
flac/1.4.2: Appending PATH environment variable: /home/chiakuma/.conan2/p/flac51168071d30f7/p/bin
glfw/3.3.8: Already installed! (23 of 34)
libunwind/1.6.2: Already installed! (24 of 34)
libusb/1.0.26: Already installed! (25 of 34)
vorbis/1.3.7: Already installed! (26 of 34)
libxml2/2.10.3: Already installed! (27 of 34)
libxml2/2.10.3: Appending PATH environment variable: /home/chiakuma/.conan2/p/libxma49011520f16a/p/bin
automake/1.16.5: Already installed! (28 of 34)
libsndfile/1.2.0: Already installed! (29 of 34)
wayland/1.21.0: Already installed! (30 of 34)
libtool/2.4.7: Already installed! (31 of 34)
libtool/2.4.7: Appending PATH env: bin_path/home/chiakuma/.conan2/p/libto9b444149dd982/p/bin
libtool/2.4.7: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
libtool/2.4.7: WARN: The use of 'unix_path_legacy_compat' is deprecated in Conan 2.0 and does not perform path conversions. This is retained for compatibility with Conan 1.x and will be removed in a future version.
xkbcommon/1.4.1: Already installed! (32 of 34)
xkbcommon/1.4.1: Appending PATH environment variable: /home/chiakuma/.conan2/p/xkbcocbb12125510f9/p/bin
pulseaudio/14.2: Already installed! (33 of 34)
sdl/2.26.1: WARN: Trying to remove corrupted source folder
sdl/2.26.1: WARN: This can take a while for big packages
sdl/2.26.1: Calling source() in /home/chiakuma/.conan2/p/sdl7f7c8fb6bac8c/s/src
ERROR: Error downloading file https://www.libsdl.org/release/SDL2-2.26.1.tar.gz: 'HTTPSConnectionPool(host='www.libsdl.org', port=443): Max retries exceeded with url: /release/SDL2-2.26.1.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb928e45e0>, 'Connection to www.libsdl.org timed out. (connect timeout=30)'))'
Waiting 5 seconds to retry...
ERROR: Error downloading file https://www.libsdl.org/release/SDL2-2.26.1.tar.gz: 'HTTPSConnectionPool(host='www.libsdl.org', port=443): Max retries exceeded with url: /release/SDL2-2.26.1.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb928e4d30>, 'Connection to www.libsdl.org timed out. (connect timeout=30)'))'
Waiting 5 seconds to retry...
ERROR: sdl/2.26.1: Error in source() method, line 194
	get(self, **self.conan_data["sources"][self.version], strip_root=True,
	ConanException: Error downloading file https://www.libsdl.org/release/SDL2-2.26.1.tar.gz: 'HTTPSConnectionPool(host='www.libsdl.org', port=443): Max retries exceeded with url: /release/SDL2-2.26.1.tar.gz (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7feb928f25b0>, 'Connection to www.libsdl.org timed out. (connect timeout=30)'))'
CMake Error at build/conan.cmake:651 (message):
  Conan install failed='1'
Call Stack (most recent call first):
  dependencies.cmake:28 (conan_cmake_install)
  src/liblgx/liblgx-common/CMakeLists.txt:5 (include)

**Desktop (please complete the following information):**
 - OS: EndeavorOS (ARCH)

**Details system information (Linux)**
If possible provide the output of:

Linux 6.2.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 07 Apr 2023 02:10:43 +0000

**Comment by ChiAkuma** [comment]
I now just return the Device to the Vendor, but i let you know that bug exist

**Comment by North-West-Wind** [comment]
The AUR package is maintained by me, so that's on me not Chris.

**Comment by ChrisAJS** [comment]
Closing.
