### ISSUE TITLE
Can we bypass conan?

### ISSUE THREAD

**Issue by ZachBacon** [ChrisAJS/lgx2userspace#31]
So my problem is the requirement of enforcing conan as a build requirement. May I ask why it's as requirement on Linux? I can understand for other platforms, but what does conan as a build requirement is supposed to bring to the table for the linux build? Especially if dependencies are met.

I guess what I'm trying to ask, is there a method to bypass the need for conan after the dependencies have been met?

**Comment by ChrisAJS** [comment]
Yeah, I'm really leaning towards rolling back conan integration for all platforms, it's been a bit of a nightmare and the speed of SDL has been gargbage compared to what you get with distributions.

Try checking out the `noconan` branch in the meantime, but I will make main remove the use of conan soon.

**Comment by ZachBacon** [comment]
Yeah I just found the noconan branch myself. Thanks!
