### ISSUE TITLE
Full 1 second audio delay

### ISSUE THREAD

**Issue by BuyMyMojo** [ChrisAJS/lgx2userspace#6]
I was outputting to the virtual cam and found the audio to output delayed

[Video](https://watch.videodelivery.net/5bc3d569ebf2ce8ffe10d769b7c71679)

**Comment by ChrisAJS** [comment]
I still need to learn the best ways to use V4L2 loopback stuff, what can happen is, if you don't have something actively trying to read frames from your `/dev/video99` device and you get the userspace driver dumping frames to it, when you finally get to opening it in say OBS, it'll start reading the beginning of the stream. 

Unfortunately the output to Pulseaudio does not wait for something to listen. 

I'll try and come up with a clever way to deal with this, it may involve some kind of controller programme.

Thank you for testing this, any recommendations would be appreciated!

**Comment by ChrisAJS** [comment]
Closing as I think this is an unachievable goal currently :(
