### ISSUE TITLE
Build for Arch

### ISSUE THREAD

**Issue by celticsamurai** [ChrisAJS/lgx2userspace#8]
Arch user here. Is there any way that I could build this for my distro? Here's what happens when I attempt to make it:
`
[  6%] Building CXX object CMakeFiles/lgx2userspace.dir/src/main.cpp.o
[ 13%] Building CXX object CMakeFiles/lgx2userspace.dir/src/lgxdevice.cpp.o
[ 20%] Building CXX object CMakeFiles/lgx2userspace.dir/src/commanddata_lgx2.cpp.o
[ 26%] Building CXX object CMakeFiles/lgx2userspace.dir/src/commanddata_lgx.cpp.o
[ 33%] Building CXX object CMakeFiles/lgx2userspace.dir/src/UsbStream.cpp.o
/home/wayne/lgx2userspace/src/UsbStream.cpp: In member function ‘virtual void libusb::UsbStream::streamSetupCommands()’:
/home/wayne/lgx2userspace/src/UsbStream.cpp:69:34: warning: comparison of integer expressions of different signedness: ‘int’ and ‘long unsigned int’ [-Wsign-compare]
   69 |                 if (actualLength != commandLength) {
      |                     ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
[ 40%] Building CXX object CMakeFiles/lgx2userspace.dir/src/SdlFrameOutput.cpp.o
[ 46%] Building CXX object CMakeFiles/lgx2userspace.dir/src/FrameBuilder.cpp.o
[ 53%] Building CXX object CMakeFiles/lgx2userspace.dir/src/V4LFrameOutput.cpp.o
[ 60%] Building CXX object CMakeFiles/lgx2userspace.dir/src/PulseAudioOutput.cpp.o
[ 66%] Building CXX object CMakeFiles/lgx2userspace.dir/src/NOOPLogger.cpp.o
/home/wayne/lgx2userspace/src/NOOPLogger.cpp: In member function ‘virtual void NOOPLogger::logTimeStart(const std::string&)’:
/home/wayne/lgx2userspace/src/NOOPLogger.cpp:3:50: warning: unused parameter ‘name’ [-Wunused-parameter]
    3 | void NOOPLogger::logTimeStart(const std::string &name) {}
      |                               ~~~~~~~~~~~~~~~~~~~^~~~
/home/wayne/lgx2userspace/src/NOOPLogger.cpp: In member function ‘virtual void NOOPLogger::logTimeEnd(const std::string&, const std::string&)’:
/home/wayne/lgx2userspace/src/NOOPLogger.cpp:5:48: warning: unused parameter ‘name’ [-Wunused-parameter]
    5 | void NOOPLogger::logTimeEnd(const std::string &name, const std::string &message) {}
      |                             ~~~~~~~~~~~~~~~~~~~^~~~
/home/wayne/lgx2userspace/src/NOOPLogger.cpp:5:73: warning: unused parameter ‘message’ [-Wunused-parameter]
    5 | void NOOPLogger::logTimeEnd(const std::string &name, const std::string &message) {}
      |                                                      ~~~~~~~~~~~~~~~~~~~^~~~~~~
[ 73%] Building CXX object CMakeFiles/lgx2userspace.dir/src/ChronoLogger.cpp.o
[ 80%] Building CXX object CMakeFiles/lgx2userspace.dir/src/OptionParser.cpp.o
[ 86%] Linking CXX executable lgx2userspace
/usr/bin/ld: cannot find -lSDL2_gfx: No such file or directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/lgx2userspace.dir/build.make:273: lgx2userspace] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/lgx2userspace.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

`

**Comment by ChuckyAtBSG** [comment]
It looks like the package that provides the development files for SDL GFX isn't installed.

Try installing `sdl2_gfx` with Pacman and retry the build.

**Comment by celticsamurai** [comment]
> It looks like the package that provides the development files for SDL GFX isn't installed.
> 
> Try installing `sdl2_gfx` with Pacman and retry the build.

Awesome! I was able to build it. However, I'm running into a new problem. This is what I get when I attempt to run it:
`
lgx2userspace v0.0.0 (main-b1431cd)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open lgx2 - is it connected? Run lsusb to check
Aborted (core dumped)

`
I ran lsusb, and it's there.

**Comment by ChuckyAtBSG** [comment]
Have you followed the udev rules guide? If so can you paste your lsusb output please.

**Comment by celticsamurai** [comment]
Oh never mind. I missed a step. It works now xD.

**Comment by ChuckyAtBSG** [comment]
No worries, I'll update the error message to include the udev rules.

Hope the tool helps you out!
