### ISSUE TITLE
Sound and Video glitched out

### ISSUE THREAD

**Issue by celticsamurai** [ChrisAJS/lgx2userspace#9]
I just updated Arch Linux (yeah I know I probably shouldn't have). Now the audio and video are completely glitched out. Here's what the video looks like.
![image](https://user-images.githubusercontent.com/101759519/182049494-3024cfd8-71ec-4c56-9cc2-9b7099132405.png)

**Comment by ChuckyAtBSG** [comment]
Does unplugging and replugging in the input hdmi sort it?

**Comment by celticsamurai** [comment]
> 

Aw shoot it does. Thanks!

**Comment by Nama** [comment]
This also happens with cables which aren't good enough (prolly with max 5gbps or something).
